slate:
  authenticate: true
  userName: admin
  password: 123456
  enable: true
  defaultTitle: API DOC
  contextPath: /slate/*
  resourcePath: slate
  index: index.html.md
  includes:
    - _errors.md
  languages:
    - ruby
    - python
    - shell
    - javascript